// Dashboard
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'

// Posts
export const CREATE_POST = 'CREATE_POST'
export const REMOVE_POST = 'REMOVE_POST'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const REQUEST_POST = 'REQUEST_POST'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const RECEIVE_POST = 'RECEIVE_POST'
export const SENDING_POST = 'SENDING_POST'
export const CREATED_POST = 'CREATED_POST'
export const CREATED_POST_ERROR = 'CREATED_POST_ERROR'
export const UPDATED_POST = 'UPDATED_POST'
export const UPDATED_POST_ERROR = 'UPDATED_POST_ERROR'

// Notifications
export const HIDING_NOTIFICATION = 'HIDING_NOTIFICATION'
export const HIDDEN_NOTIFICATION = 'HIDDEN_NOTIFICATION'
export const TIME_LEFT_NOTIFICATION = 'TIME_LEFT_NOTIFICATION'
export const TIME_LEFT_CANCELLED_NOTIFICATION = 'TIME_LEFT_CANCELLED_NOTIFICATION'
export const NOTIFICATION_SUCCESS = 'success'
export const NOTIFICATION_INFO = 'info'
export const NOTIFICATION_ERROR = 'danger'
export const NOTIFICATION_WARNING = 'warning'
export const NOTIFICATION_PRIMARY = 'primary'

// Login
export const SENDING_LOGIN = 'SENDING_LOGIN'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'

// Intl
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
